const professions = [
  { label: 'Accountant' },
  { label: 'Actor' },
  { label: 'Actuary' },
  { label: 'Aircraft pilot' },
  { label: 'Architect' },
  { label: 'Artist' },
  { label: 'Athlete' },
  { label: 'Barbershop' },
  { label: 'Broker' },
  { label: 'Butcher' },
  { label: 'Chef' },
  { label: 'Cleaner' },
  { label: 'Clinical Psychiatrist' },
  { label: 'Dental hygienist' },
  { label: 'Dentist' },
  { label: 'Designer' },
  { label: 'Dietitian' },
  { label: 'Electrician' },
  { label: 'Engineer' },
  { label: 'Engineering technologist' },
  { label: 'Firefighter' },
  { label: 'Hairdresser' },
  { label: 'Health professional' },
  { label: 'Judge' },
  { label: 'Laborer' },
  { label: 'Laborer' },
  { label: 'Lawyer' },
  { label: 'Librarian' },
  { label: 'Mechanic' },
  { label: 'Medical laboratory scientist' },
  { label: 'Midwife' },
  { label: 'Musician' },
  { label: 'Operator' },
  { label: 'Pharmacist' },
  { label: 'Physician' },
  { label: 'Physiotherapist' },
  { label: 'Plumber' },
  { label: 'Police officer' },
  { label: 'Radiographer' },
  { label: 'Respiratory therapist' },
  { label: 'Scientist' },
  { label: 'Secretary' },
  { label: 'Software Developer' },
  { label: 'Statistician' },
  { label: 'Surgeon' },
  { label: 'Surveyor' },
  { label: 'Teacher' },
  { label: 'Technician' },
  { label: 'Tradesman' },
  { label: 'Veterinary physician' },
  { label: 'Waiter' },
];

module.exports.allProfessions = () => professions;
